flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- pandoc-citeproc-0.16.1
- skylighting-0.7.7
- git: https://github.com/harfangk/skylighting.git
  commit: 47412251dd4709b3527c2b89f4b33e08a8ade3e0
  subdirs:
    - skylighting-core
- ipynb-0.1
- texmath-0.11.2
ghc-options:
   "$locals": -fhide-source-paths -XNoImplicitPrelude
resolver: lts-13.9
